config/routes.rb
Push2party::Application.routes.draw do

  resources :sponsors

  resources :ads

  resources :orders

  resources :users

  resources :items do
    match 'by_parent_id', :on => :collection
    match 'by_parent_id_with_children', :on => :collection
  end

  resources :gallery_images

  resources :galleries

  resources :coupons

  resources :combos
  

	match 'ping' => 'users#ping'
	
	match 'ordenes' => 'display#index'
	
	match 'detalle' => 'display#detail', :as => :detalle

end

app/models/ad.rb
class Ad < ActiveRecord::Base
  attr_accessible :image_url, :visible
end

app/models/combo.rb
class Combo < ActiveRecord::Base
  attr_accessible :description, :image_url, :name, :price, :visible, :priority
end

app/models/coupon.rb
class Coupon < ActiveRecord::Base
  attr_accessible :image_url, :visible, :name, :image_url_thumb
end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
  attr_accessible :name, :visible
  has_many :gallery_images
end

app/models/gallery_image.rb
class GalleryImage < ActiveRecord::Base
  attr_accessible :description, :gallery_id, :image_url, :visible, :image_url_thumb
  belongs_to :gallery
end

app/models/item.rb
class Item < ActiveRecord::Base
  attr_accessible :description, :name, :parent_id, :price, :visible, :priority
end

app/models/order.rb
class Order < ActiveRecord::Base
  attr_accessible :data, :rp_id
end

app/models/sponsor.rb
class Sponsor < ActiveRecord::Base
  attr_accessible :active, :image_url, :name, :priority
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :firstname, :lastname, :phone, :subscribed, :gender, :dob
end

app/controllers/ads_controller.rb
class AdsController < ApplicationController
  # GET /ads
  # GET /ads.json
  def index
    @ads = Ad.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @ads }
    end
  end

  # GET /ads/1
  # GET /ads/1.json
  def show
    @ad = Ad.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @ad }
    end
  end

  # GET /ads/new
  # GET /ads/new.json
  def new
    @ad = Ad.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @ad }
    end
  end

  # GET /ads/1/edit
  def edit
    @ad = Ad.find(params[:id])
  end

  # POST /ads
  # POST /ads.json
  def create
    @ad = Ad.new(params[:ad])

    respond_to do |format|
      if @ad.save
        format.html { redirect_to @ad, notice: 'Ad was successfully created.' }
        format.json { render json: @ad, status: :created, location: @ad }
      else
        format.html { render action: "new" }
        format.json { render json: @ad.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /ads/1
  # PUT /ads/1.json
  def update
    @ad = Ad.find(params[:id])

    respond_to do |format|
      if @ad.update_attributes(params[:ad])
        format.html { redirect_to @ad, notice: 'Ad was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @ad.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ads/1
  # DELETE /ads/1.json
  def destroy
    @ad = Ad.find(params[:id])
    @ad.destroy

    respond_to do |format|
      format.html { redirect_to ads_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/gallery_images_controller.rb
class GalleryImagesController < ApplicationController
  # GET /gallery_images
  # GET /gallery_images.json
  def index
    @gallery_images = GalleryImage.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @gallery_images }
    end
  end

  # GET /gallery_images/1
  # GET /gallery_images/1.json
  def show
    @gallery_image = GalleryImage.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @gallery_image }
    end
  end

  # GET /gallery_images/new
  # GET /gallery_images/new.json
  def new
    @gallery_image = GalleryImage.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @gallery_image }
    end
  end

  # GET /gallery_images/1/edit
  def edit
    @gallery_image = GalleryImage.find(params[:id])
  end

  # POST /gallery_images
  # POST /gallery_images.json
  def create
    @gallery_image = GalleryImage.new(params[:gallery_image])

    respond_to do |format|
      if @gallery_image.save
        format.html { redirect_to @gallery_image, notice: 'Gallery image was successfully created.' }
        format.json { render json: @gallery_image, status: :created, location: @gallery_image }
      else
        format.html { render action: "new" }
        format.json { render json: @gallery_image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /gallery_images/1
  # PUT /gallery_images/1.json
  def update
    @gallery_image = GalleryImage.find(params[:id])

    respond_to do |format|
      if @gallery_image.update_attributes(params[:gallery_image])
        format.html { redirect_to @gallery_image, notice: 'Gallery image was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @gallery_image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gallery_images/1
  # DELETE /gallery_images/1.json
  def destroy
    @gallery_image = GalleryImage.find(params[:id])
    @gallery_image.destroy

    respond_to do |format|
      format.html { redirect_to gallery_images_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  # GET /items
  # GET /items.json
  def index
    @items = Item.order("ID ASC")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @items }
    end
  end

  # GET /items/1
  # GET /items/1.json
  def show
    @item = Item.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @item }
    end
  end

  # GET /items/new
  # GET /items/new.json
  def new
    @item = Item.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @item }
    end
  end

  # GET /items/1/edit
  def edit
    @item = Item.find(params[:id])
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(params[:item])

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render json: @item, status: :created, location: @item }
      else
        format.html { render action: "new" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /items/1
  # PUT /items/1.json
  def update
    @item = Item.find(params[:id])

    respond_to do |format|
      if @item.update_attributes(params[:item])
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item = Item.find(params[:id])
    @item.destroy

    respond_to do |format|
      format.html { redirect_to items_url }
      format.json { head :no_content }
    end
  end

  def by_parent_id
    @items = Item.where("parent_id = ?", params[:parent_id])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @items }
    end
  end
  
  def by_parent_id_with_children
    result = []
    @items = Item.where("parent_id = ?", params[:parent_id])
    @items.each do |item|
      item[:children] = Item.where("parent_id = ? and price is not null and visible = ?", item.id, true).order('PRIORITY DESC')
      if item[:children].size != 0
        result << item
      end
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: result }
    end
  end

end

app/helpers/ads_helper.rb
module AdsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/combos_helper.rb
module CombosHelper
end

app/helpers/coupons_helper.rb
module CouponsHelper
end

app/helpers/display_helper.rb
module DisplayHelper
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/helpers/gallery_images_helper.rb
module GalleryImagesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/sponsors_helper.rb
module SponsorsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/gallery_images/_form.html.erb
<%= form_for(@gallery_image) do |f| %>
  <% if @gallery_image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gallery_image.errors.count, "error") %> prohibited this gallery_image from being saved:</h2>

      <ul>
      <% @gallery_image.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br />
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :image_url_thumb %><br />
    <%= f.text_field :image_url_thumb %>
  </div>
  <div class="field">
    <%= f.label :gallery_id %><br />
    <%= f.text_field :gallery_id %>
  </div>
  <div class="field">
    <%= f.label :visible %><br />
    <%= f.check_box :visible %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/gallery_images/edit.html.erb
<h1>Editing gallery_image</h1>

<%= render 'form' %>

<%= link_to 'Show', @gallery_image %> |
<%= link_to 'Back', gallery_images_path %>

app/views/gallery_images/index.html.erb
<h1>Listing gallery_images</h1>

<table>
  <tr>
    <th>Description</th>
    <th>Image url</th>
    <th>Image thumb</th>
    <th>Gallery</th>
    <th>Visible</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @gallery_images.each do |gallery_image| %>
  <tr>
    <td><%= gallery_image.description %></td>
    <td><%= gallery_image.image_url %></td>
    <td><%= gallery_image.image_url_thumb %></td>
    <td><%= gallery_image.gallery_id %></td>
    <td><%= gallery_image.visible %></td>
    <td><%= link_to 'Show', gallery_image %></td>
    <td><%= link_to 'Edit', edit_gallery_image_path(gallery_image) %></td>
    <td><%= link_to 'Destroy', gallery_image, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Gallery image', new_gallery_image_path %>

app/views/gallery_images/new.html.erb
<h1>New gallery_image</h1>

<%= render 'form' %>

<%= link_to 'Back', gallery_images_path %>

app/views/gallery_images/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Description:</b>
  <%= @gallery_image.description %>
</p>

<p>
  <b>Image url:</b>
  <%= @gallery_image.image_url %>
</p>

<p>
  <b>Image url thumb:</b>
  <%= @gallery_image.image_url_thumb %>
</p>

<p>
  <b>Gallery:</b>
  <%= @gallery_image.gallery_id %>
</p>

<p>
  <b>Visible:</b>
  <%= @gallery_image.visible %>
</p>


<%= link_to 'Edit', edit_gallery_image_path(@gallery_image) %> |
<%= link_to 'Back', gallery_images_path %>